spring.application.name=demo

server.port=8080

#database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/eshop_demo_db
spring.datasource.username=postgres
spring.datasource.password=870417
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
