spring.application.name=demo

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/eshop_demo_db
spring.datasource.username=postgres
spring.datasource.password=870417
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true